# executes all cells (e.g. numerical examples) in all notebooks 
# by using sphinx with the nbsphinx extension

name: Sphinx build

on:
  push:
  pull_request:
  
  schedule:
    - cron:  '30 1 1,15 * *'

jobs:
  linux_py3_12:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - run: sudo apt-get install libsndfile1 pandoc
      - run: pip install -r requirements.txt
      - run: pip install -r ci/requirements.txt   
      - run: python -m sphinx . _build/ -b html
